config/routes.rb
Rails.application.routes.draw do
  root "users#index"
  get "users/" => "users#index"
  get "signup" => "users#new", as: :new_user
  get"users/:id" => "users#show", as: :user
  get "users/:id/edit" => "users#edit", as: :edit_user
  post "users/" => "users#create"
  patch "users/:id" => "users#update"
  delete "users/:id" => "users#destroy"
  get "/login" => "sessions#new"
  post "/login" => "sessions#create"
  delete "/logout" => "sessions#destroy"
  post "users/:id/statuses" => "statuses#create", as: :user_statuses

end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/models/session.rb
class Session < ActiveRecord::Base
	validates :username, presence: true
	validates :password, presence: true
end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :statuses
      before_save :format_user_input

	attr_reader :password

  def password=(unencrypted_password)
  	unless unencrypted_password.empty?
    		@password = unencrypted_password
    		self.password_digest = BCrypt::Password.create(unencrypted_password)
    	end
  end

  def authenticate(unencrypted_password)
    if BCrypt::Password.new(self.password_digest) ==  unencrypted_password
      return self
    else
      return false
    end
  end

  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :email, presence: true, uniqueness: { case_sensitive: false}, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validates :password, presence: true, confirmation: true, length: { in: 6..20 }
  private
  def format_user_input
    self.email = self.email.downcase
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  include SessionsHelper

	private
	def current_user
	 	@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def new
	end

	def create
	end

	def edit
	end

	def update
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

 	 def create
 		 user = User.find_by(username: params[:login][:username])
 		 logger.debug(user)
  		if user && user.authenticate(params[:login][:password])
    			session[:user_id] = user.id.to_s
   			redirect_to users_path
  		else
  			flash.now[:error] = "The email or password you provided does not match our records"	
    			render :new
  		end
	end
	
	def destroy
		session.delete(:user_id)
		redirect_to login_path
	end

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
	def create
		@user = User.find(params[:id])
		@status = @user.statuses.new(params.require(:status).permit(:body))
		@status.save
		redirect_to user_path(@user)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_login, except: [:new, :create]
	before_action :authorized?, only: [:edit, :update]

	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
		@status = Status.new
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			[session[:user_id] = @user.id.to_s]
			flash[:welcome] = "Thanks for signing up!"
			redirect_to users_path
		else
			render :new
		end
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

		if @user.update_attributes(user_params)
			redirect_to users_path
		else
			render :edit
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to users_path
	end
	private

	def require_login
		unless logged_in?
			flash[:error] = "You must be logged in to access that page."
			redirect_to login_path
		end
	end

	def authorized?
		unless current_user == User.find(params[:id])
			flash[:error] = "You are not authorized to access that page."
			redirect_to user_path
		end
	end

	def user_params
		params.require(:user).permit(:username, :password, :first_name, :last_name, :email, :age, :gender, :looking_for)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
def logged_in?
	session[:user_id] != nil
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Surface2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid wooden">
	<nav>
	<% if logged_in? %>
		<p>Logged in as: <%= current_user.username  %> | <%= link_to 'Log Out', logout_path, method: :delete  %></p>
	<% else %>
		<div>
			<%= link_to 'Log In', login_path  %> | <%= link_to 'Sign Up', new_user_path  %>
		</div>
	<% end %>
	</nav>

	<% if flash[:welcome] %>
	<h4 class="bg-success flash">
		<%= flash[:welcome]  %></h4>
	<% end %>

	<% if flash[:error] %>
	<h4 class="bg-danger flash">
		<%= flash[:error]  %></h4>
	<% end %>
<%= yield %>
</div>
</body>
</html>

app/views/profiles/new.html.erb
<div>
	<section>
		<%= form_for @profile do |f| %>
			<div>
				<%= f.label :first_name %>
				<%= f.text_field :first_name  %>
			</div>

			<div>
				<%= f.label :last_name %>
				<%= f.text_field :last_name  %>
			</div>

			<div>
				<%= f.label :age %>
				<%= f.number_field :age  %>
			</div>

			<div>
				<%= f.label :gender %>
				<%= f.text_field :gender  %>
			</div>

			<div>
				<%= f.label :looking_for %>
				<%= f.text_field :looking_for  %>
			</div>

			<div>
				<%= f.label :first_name %>
				<%= f.text_field :first_name  %>
			</div>

		<% end %>
	</section>
</div>

app/views/users/edit.html.erb
<div class="container">
	<div class="masthead">
		<h1>Edit this profile!</h1>
	</div>
	<hr>

	<% if @user.errors.any? %>
		<div>
			<h4 class="text-danger">
			 	<%= pluralize(@user.errors.count, "error")  %>
			 </h4>
			 <ul class="list-group-item list-group-item-danger">
				<% @user.errors.full_messages.each do |msg| %>
				<li class= "list-group-item list-group-item-danger">
					<%= msg.downcase  %>
				</li>
				<% end %>
			 </ul>
		</div>
		<% end %>
		<br>
	
		<div class="row col-sm-3">
		<%= form_for @user, class: "form-horizontal" do |f| %>
		
			<div class="form-group">
				<%= f.label :username %>
				<%= f.text_field :username, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= f.label :password %>
				<%= f.password_field :password, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= f.label :password_confirmation %>
				<%= f.password_field :password_confirmation, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= f.label :first_name %>
				<%= f.text_field :first_name, class: "form-control"%>
			</div>

			<div class="form-group">
				<%= f.label :last_name %>
				<%= f.text_field :last_name, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= f.label :email %>
				<%= f.text_field :email, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= f.label :age %>
				<%= f.number_field :age, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= f.label :gender %>
				<%= f.text_field :gender, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= f.label :looking_for %>
				<%= f.text_field :looking_for, class: "form-control" %>
			</div>
			<div class="form-group">
			<%= f.submit "Submit these changes!", class: "btn btn-success" %>
			</div>
			<div class="form-group">
				<%= link_to "Back to the list!", users_path, class: "btn btn-default" %>
			</div>
	
		<% end %>
	
	</div>
</div>

app/views/users/index.html.erb
<div class="container-fluid">
<div>
	
<div class="jumbotron">
	<h1> Check Out Other Users!</h1>
	<p class="lead">See what other users are saying!</p>
	
	<%= link_to "Join now!", new_user_path, class: "btn btn-primary" %>
</div>

	<div class="row">
	
		<div class="col-md-4">
			<blockquote class="well">
				 <p>You are the Rails beneath my Ruby</p>
				 <footer>Mikel Pacheco</footer>
			</blockquote>
		</div>

		<div class="col-md-4">
			<blockquote class="well">
				 <p>After 5:30 pm on Friday, I just want to talk about life</p>
				 <footer>Jimmy Garson</footer>
			</blockquote>
		</div>

		<div class="col-md-4">
			<blockquote class="well">
				 <p>Circle puppy!</p>
				 <footer>Glenn Harris</footer>
			</blockquote>
		</div>
	</div>

<ul class="list-unstyled">

	<% @users.each do |user| %>
		
		 	<div class="col-md-4">
			<li class="well-sm">
				<%= image_tag user.image.url, class: "img-circle" %>
				<strong> <%= user.username %> </strong> - <%= user.age %> years old - <%= user.gender %> looking for <%= user.looking_for %> 
				<%= link_to "More info", user_path(user), class: "btn btn-info" %>
			</li>
			</div>
		
	<% end %>

</ul>


</div>

app/views/users/new.html.erb
<div class="container">
<div class="jumbotron">
	<h1>Join Surface Today</h1>
	<p class="lead">and Start Connecting Immediately!</p>
	<%= link_to "Log In", login_path, class: "btn btn-info" %>
	<%#= link_to "Log in!" class: "btn btn-success"  %>
</div>

<% if @user.errors.any? %>
<div>
	<h4 class="text-danger">
	 	<%= pluralize(@user.errors.count, "error")  %>
	 </h4>
	 <ul class="list-group-item list-group-item-danger">
		<% @user.errors.full_messages.each do |msg| %>
		<li class= "list-group-item list-group-item-danger">
			<%= msg.downcase  %>
		</li>
		<% end %>
	 </ul>
</div>
<% end %>
<br>



	<div class="col-md-3 col-md-offset-1">
		
			<%= form_for @user do |f| %>
			<div class="form-group">
				<%= f.label :username %>
				<%= f.text_field :username, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= f.label :password, "Password" %>
				<%= f.password_field :password, class: "form-control" %>
			</div>

			<div class="form-group">
				<%= f.label :password_confirmation, "Password" %>
				<%= f.password_field :password_confirmation, class: "form-control" %>
			</div>


			<div class="form-group">
				<%= f.label :email %>
				<%= f.text_field :email, class: "form-control" %>
			</div>

			
			<div class="form-group">
				<%= f.submit "Join now!", class: "btn btn-primary" %>
			</div>
		 	<div class="form-group">
				<%= link_to "Back to the list!", users_path, class: "btn btn-default" %>
			</div> 
		
		<% end %>

	<br>
	</div>
</div>

app/views/users/show.html.erb
<div class="jumbotron">

	 	<img class="img-circle" style="float: left; max-width: 200px; max-height: 200px" src="http://fillmurray.com/200/200">

	


	<%= link_to "Edit this user!", edit_user_path(@user), class: "btn btn-warning" %>
	<%= link_to "Back to the list!", users_path, class: "btn btn-info" %>
	<%= link_to "Delete this user!", user_path, class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?"} %>
</div>
<div class="container">
	<div class="row">
		<section>
			<h2>Statuses</h2>
			<% @user.statuses.each do |status| %>
				<div class="col-md-4">

					<h3>#status<%= @user.statuses.index(status) +1 %></h3>
					<p><strong><%= status.body %></strong> </p>
				</div>
			<% end %>	
		</section>
	</div>
	<br>
	<div class="row">
		<section>
			<h2>Add a new status!</h2>
			<%= form_for [@user, @status] do |f| %>
				<div>
			
					<%= f.label :body, "Status" %>
					<%= f.text_area :body, class: "form-control" %>
				
				</div>
				<br>
				<%= f.submit "Add your status!", class: "btn btn-primary" %>
			<% end %>
		</section>
	</div>
</div>